### ISSUE TITLE
Unable to mock data !

### ISSUE THREAD

**Issue by mohamedabuzenah** [yuanzhaokang/NorseAttack-like#4]
I really like this project . I have installed everything but im unable to mock data when i open localhost:4000/wsSender/ when i put longitude and latitude the send button is un-clickable . Can you assist on this .Thank you

**Comment by yuanzhaokang** [comment]
> I really like this project . I have installed everything but im unable to mock data when i open localhost:4000/wsSender/ when i put longitude and latitude the send button is un-clickable . Can you assist on this .Thank you

**Comment by yhdjyyzk** [comment]
> I really like this project . I have installed everything but im unable to mock data when i open localhost:4000/wsSender/ when i put longitude and latitude the send button is un-clickable . Can you assist on this .Thank you

Thanks for following this project. Is there something wrong in browser console？If you run according to README，it will wrok well.

**Comment by mohamedabuzenah** [comment]
May i know which browser you used for this project ? . Thanks

**Comment by yhdjyyzk** [comment]
> May i know which browser you used for this project ? . Thanks

Chrome 71.0.3578.98
